apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: producer
build:
  artifacts:
    - image: sayed/demo
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - target/classes/META-INF/dekorate/kubernetes.yml
portForward:
  - resourceType: deployment
    resourceName: demo
    namespace: default
    port: 8080
    localPort: 8080