---
project:
  root: file:///home/sayed/github_repo/producer/
  dekorateInputDir: null
  dekorateOutputDir: META-INF/dekorate
  dekorateMetaDir: ../.dekorate
  buildInfo:
    name: demo
    version: 0.0.1-SNAPSHOT
    packaging: jar
    buildTool: maven
    buildToolVersion: 3.6.3
    outputFile: file:///home/sayed/github_repo/producer/target/demo-0.0.1-SNAPSHOT.jar
    classOutputDir: file:///home/sayed/github_repo/producer/target/classes/
    resourceDir: file:///home/sayed/github_repo/producer/target/classes/
  scmInfo:
    root: file:///home/sayed/github_repo/producer/
    branch: develop
    commit: f0d7a012475e1e5d2ae3fd14fa39742f47805a76
    remote:
      '[remote "origin"]': https://github.com/sayed-moin-ahmed/producer.git
